services:
  - type: web
    name: lala-store-frontend
    runtime: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: lala-store-api
    runtime: node
    rootDir: Serveur Backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
